### ISSUE TITLE
Erroring if ID variable not the first column in data

### ISSUE THREAD

**Issue by taryue** [graemeleehickey/joineRML#59]
Hi, Thanks for your great R package. I was trying to run your package for my little toy example, but I keep having the following error: 

Error in status[length(id.col)] <- survdat2[survdat2$id == id.col[1],  : 
  replacement has length zero

I don't know what is wrong. My code is, 
fit1 <- mjoint(formLongFixed = y_long ~ time_stack + Z_rep,
               formLongRandom = ~ 1 | id,
               formSurv = Surv(survtime_long, delta_long) ~ Z_rep,
               timeVar = "time_stack", data = data_init_flag, 
               control = list(nMCscale = 2, burnin = 5))  

I attach my toy data here. 
[long_surv_toy.txt](https://github.com/graemeleehickey/joineRML/files/2206670/long_surv_toy.txt)

Thanks for your help. 
Yue

**Comment by taryue** [comment]
Oops, I figured out the reason. The id variable has to be the first column.

**Comment by graemeleehickey** [comment]
Interesting. ID should not need to be the first column in joineRML. I've
cc'ed Pete Philipson who has taken over maintenance.

**Comment by graemeleehickey** [comment]
@petephilipson -- Can you investigate please?

**Comment by ellessenne** [comment]
Hi, I started looking into this and can confirm the bug:

``` r
library(joineRML)
#> Loading required package: nlme
#> Loading required package: survival
data(heart.valve)
hvd <- heart.valve[!is.na(heart.valve$log.grad) & !is.na(heart.valve$log.lvmi), ]

# Put ID last
hvd <- hvd[, c(2:ncol(hvd), 1)]

# Fit model
set.seed(1)
fit1 <- mjoint(
  formLongFixed = log.lvmi ~ time + age,
  formLongRandom = ~ time | num,
  formSurv = Surv(fuyrs, status) ~ age,
  data = hvd,
  timeVar = "time",
  control = list(nMCscale = 2, burnin = 5)
)
#> Error in status[length(id.col)] <- survdat2[survdat2$id == id.col[1], : replacement has length zero
```

<sup>Created on 2020-03-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

#63 is a duplicate (I'm closing it), let's continue the discussion here.
