### ISSUE TITLE
Multiple random effects equations

### ISSUE THREAD

**Issue by PradeepVirdee** [graemeleehickey/joineRML#73]
Hi,

I am including time (range 0-5 years) in my formLongFixed using penalised splines, with a knot at each year from time=1 to time=4 years. Following the approach by Fitzmaurice 2011 (Applied Longitudinal Analysis), I am including only one spline as a fixed effect and am trying to include all splines as random effects but I can't seem to include a second random effects equations in formLongRandom.

```
# Make splines for time
data$time1 = (data$time - 1)*I(data$time > 1)
data$time2 = (data$time - 2)*I(data$time > 2)
data$time3 = (data$time - 3)*I(data$time > 3)
data$time4 = (data$time - 4)*I(data$time > 4)

# Run model
set.seed(123456)
jointmodel = mjoint(
  formLongFixed = list("hb" = Hb ~ time + time4 + age,
                       "plat" = Plat ~ time + time3 + age),
  formLongRandom = list("hb" = ~ (time | id) + (time1 + time2 + time3 + time4 | 1),
                       "plat" = ~ (time | id) + (time1 + time2 + time3 + time4 | 1)),
  formSurv = Surv(futime2y, crc2y) ~ age,
  data = data,
  timeVar = "time",
)
summary(jointmodel)
```

I get this error: 
Error in nlme::splitFormula(formLongRandom[[1]], "|")[[2]] : 
  subscript out of bounds

Is it possible to have multiple random effects equations? Or would you suggest a different approach to coding?

**Comment by graemeleehickey** [comment]
Unfortunately this exact model cannot be fitted in joineRML. The random effects model expects something of the sort `1 + f(time) | id` or simpler. In principle, you could wrap a transform in the I() function,

e.g. `formLongRandom = ~(time + I(time* (time > 3)) | id`, but you would need the spline slope to be random rather than fixed as you have above.

**Comment by graemeleehickey** [comment]
Closing as no further response.
