### ISSUE TITLE
Fit mjoint using multiple cores in parallel

### ISSUE THREAD

**Issue by PradeepVirdee** [graemeleehickey/joineRML#74]
Hi Graeme,

I'm using the joineRML package to fit a joint model on a large dataset obtained from electronic patient records. I am building models on my eligible patient sample of ~80,000 males (~500,000 observations) and ~130,000 females (~650,000 observations) separately, I've been testing on smaller samples and found that larger sample sizes take exponentially longer. I intend to a use powerful computer/cluster. Is it possible for mjoint to use multiple cores in parallel to speed up the process?

I notice bootSE has built-in controls for this. Is this something mjoint has? If not, do you know of any workarounds to use multiple cores?

Thanks,
Pradeep

**Comment by graemeleehickey** [comment]
mjoint() cannot be parellised; however, it can be made faster by using the
quasi MC option. See here:  https://core.ac.uk/download/pdf/323306058.pdf.

**Comment by PradeepVirdee** [comment]
Thanks Graeme, I'll look into this.
